os: linux
dist: xenial
branches:
  only:
    - master
    
notifications:
  email: false

matrix:
  fast_finish: true
  include:
    # - name: "python"
    #   language: python
    #   env:
    #     - "CC=/usr/bin/gcc"
    #     - "CXX=/usr/bin/g++"

    - name: "cpp"
      language: cpp
      env:
        - "CC=/usr/bin/gcc"
        - "CXX=/usr/bin/g++"
      addons:
        apt:
          packages:
            - cmake
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build . -- -j2
        - ctest

    - name: "rust"
      language: rust
      rust: 
        - stable
        - beta
      script:
        - cargo test